#!/usr/bin/env bash
# Same 300 questions, notes+textbook generated by Qwen3-8B instead of OTel-31B; scored on the same card after.
set -uo pipefail
ROOT=$HOME/projects/teleqna/runs/teleqna-8b; PY=$HOME/venv-vllm-nightly/bin/python
export PATH="$(dirname "$PY"):$PATH" HF_HUB_OFFLINE=1 HF_DATASETS_OFFLINE=1 TOKENIZERS_PARALLELISM=false OMP_NUM_THREADS=8 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export CUDA_VISIBLE_DEVICES="${CARDS:-5}"
cd "$ROOT"
echo "#### GEN8B START $(date -Iseconds)"
timeout --foreground 7200 "$PY" -u code/kit/gen_kit_pilot.py --n 300 --gen "$HOME/projects/_shared/models/Qwen3-8B" --views notes,textbook --tag pilot8b > logs/kit_pilot8b_gen.log 2>&1
grep -q KIT_PILOT_DONE logs/kit_pilot8b_gen.log || { echo "ABORT gen"; tail -3 logs/kit_pilot8b_gen.log; exit 1; }
echo "#### GEN8B DONE $(date -Iseconds)"
sed -e 's#data/kit/pilot_sample.json#data/kit/pilot8b_sample.json#; s#data/kit/pilot_views.jsonl#data/kit/pilot8b_views.jsonl#; s#data/eval/kit_{name}#data/eval/kit8b_{name}#; s#-> kit_{name}#-> kit8b_{name}#' code/kit/build_kit_eval.py > code/kit/build_kit_eval_8b.py
"$PY" -u code/kit/build_kit_eval_8b.py || { echo "ABORT build"; exit 1; }
for ARM in kit8b_notes kit8b_textbook kit8b_combo_all; do
  f=data/eval/$ARM.jsonl; [ -f "$f" ] || continue
  echo "#### $ARM START $(date -Iseconds)"
  timeout --foreground 3600 "$PY" -u code/eval_dev_vllm.py --base "$HOME/projects/_shared/models/Qwen3-8B" --data "$f" \
    --out-dir results/landscape --tag "${ARM}_q3_8b" --with-base --max-new 512 --tp 1 --gpu-mem 0.90 --max-model-len 16384 > logs/${ARM}_eval.log 2>&1
  echo "#### $ARM DONE rc=$? $(date -Iseconds)"
done
echo "#### KIT8B_ALL_DONE"
