#!/usr/bin/env bash
# Hypothesis B arm on the tier-1 keep windows (15,760): self-contained recall-QA x20 per window generated by the 8B,
# mixed with the anchor-fix pack (docs + views), trained from BASE (lr 1e-5, 1 epoch, cards 0-3) — compared with the
# anchor-fix arm (74.14). Also a recall probe on held-out QA for base vs arm. Cards 0-3 only.
set -uo pipefail
ROOT=$HOME/projects/teleqna/runs/teleqna-8b; PY=$HOME/venv-vllm-nightly/bin/python
export PATH="$(dirname "$PY"):$PATH" HF_HUB_OFFLINE=1 HF_DATASETS_OFFLINE=1 TOKENIZERS_PARALLELISM=false OMP_NUM_THREADS=8 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True NCCL_NVLS_ENABLE=0
cd "$ROOT"; mkdir -p data/kit/recall; CARDS="${CARDS:-0,1,2,3}"; NP=$(echo "$CARDS" | tr "," "\n" | wc -l); ACC=$(( 32 / (NP * 2) ))
until grep -q "VD_CHAIN_DONE round=5\|ABORT\|rc=[1-9]" logs/vd5_chain.log 2>/dev/null; do sleep 120; done
for i in $(seq 1 480); do busy=0; for c in $(echo "$CARDS" | tr "," " "); do used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i $c); [ "$used" -le 1000 ] || busy=1; done; [ "$busy" = 0 ] && break; sleep 30; done
echo "#### RECALL GEN START $(date -Iseconds)"
for s in 0 1 2 3; do c=$(echo "$CARDS" | cut -d, -f$((s+1))); CUDA_VISIBLE_DEVICES=$c "$PY" -u code/kit/gen_recall_qa.py --shard $s --nshards 4 --seed $((1200+s)) --k 20 > logs/recall_gen_s$s.log 2>&1 & done; wait
grep -h "train rows\|Traceback" logs/recall_gen_s*.log | cut -c1-200
cat data/kit/recall/rows_s*.jsonl > data/kit/recall/rows.jsonl
"$PY" -u code/kit/pack_chat.py --rows data/kit/recall/rows.jsonl --out data/kit/recall/pack_qa > logs/recall_pack.log 2>&1; tail -2 logs/recall_pack.log
"$PY" -u code/kit/pack_concat.py --packs data/kit/tier1/pack_agree,data/kit/recall/pack_qa --out data/kit/recall/pack_mix > logs/recall_mix.log 2>&1; tail -2 logs/recall_mix.log
grep -q PACK_DONE logs/recall_mix.log || { echo "ABORT recall pack"; exit 1; }
echo "#### RECALL PROBE base START $(date -Iseconds)"
CUDA_VISIBLE_DEVICES=$(echo "$CARDS" | cut -d, -f1) "$PY" -u code/kit/recall_probe.py --ckpt $HOME/projects/_shared/models/Qwen3-8B --tag base > logs/recall_probe_base.log 2>&1; grep -E "recall|^   " logs/recall_probe_base.log
CUDA_VISIBLE_DEVICES=$(echo "$CARDS" | cut -d, -f2) "$PY" -u code/kit/recall_probe.py --ckpt models/kit/vd3/ep1 --tag vd3 > logs/recall_probe_vd3.log 2>&1; grep -E "recall" logs/recall_probe_vd3.log
for i in $(seq 1 480); do busy=0; for c in $(echo "$CARDS" | tr "," " "); do used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i $c); [ "$used" -le 1000 ] || busy=1; done; [ "$busy" = 0 ] && break; sleep 30; done
echo "#### RECALL TRAIN START cards=$CARDS $(date -Iseconds)"
CUDA_VISIBLE_DEVICES=$CARDS timeout --foreground 86400 torchrun --nproc_per_node=$NP --master_port=29730 code/kit/train_tier1.py --pack data/kit/recall/pack_mix --out models/kit/recall --epochs 1 --bs 2 --acc $ACC --lr 1e-5 > logs/recall_train.log 2>&1
echo "#### RECALL TRAIN DONE rc=$? $(date -Iseconds)"; grep -q TRAIN_DONE logs/recall_train.log || exit 1
CKPT=models/kit/recall/ep1 TAG=recall_ep1 CARDS=$(echo "$CARDS" | cut -d, -f1) bash jobs/eval_ckpt.sh > logs/eval_recall.log 2>&1; grep RESULT logs/eval_recall.log
CUDA_VISIBLE_DEVICES=$(echo "$CARDS" | cut -d, -f2) "$PY" -u code/kit/recall_probe.py --ckpt models/kit/recall/ep1 --tag recall_ep1 > logs/recall_probe_arm.log 2>&1; grep -E "recall" logs/recall_probe_arm.log
echo "#### RECALL_CHAIN_DONE $(date -Iseconds)"
